---
title: "Codebook"
author: "Shiraz"
date: "05/07/2020"
output: html_document

##The original data was transformed by

1. Merging the training and the test sets to create one data set.
2. Extracting only the measurements on the mean and standard deviation for each measurement.
3. Using descriptive activity names to name the activities in the data set
4. Appropriately labeling the data set with descriptive activity names.
5. Creating a second, independent tidy data set with the average of each variable for each activity and each subject.


##About R script

File with R code "run_analysis.R" perform 5 following steps (in accordance assigned task of course work)


# Downloading
Url = Download link
Path = Directory Path
Files = Recursive file creation

# Assigning files
# All file names
labelTrain
labelTest
subTrain
subTest  
setTrain
setTest

# Merging
rSub = rbind subs
rLabel = rbind labels
rSet = rbind set
rSetNames = row set names
dataCombine = combine columns
merge = cbind the rest of the data

# Read in Labels
activityLabels = Activity Labels data


newData = Tidy data
